<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Platforms>x64</Platforms>
    <Configurations>Debug;Release</Configurations>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <InformationalVersion>$(AssemblyVersion)</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="PortalBridgeUpstreamCommit" Value="405d278054abfed20fc470800056df72d42f2b82" />
    <ProjectReference Include="..\MHServerEmu.Core\MHServerEmu.Core.csproj" />
    <ProjectReference Include="..\MHServerEmu.DatabaseAccess\MHServerEmu.DatabaseAccess.csproj" />
    <ProjectReference Include="..\MHServerEmu.PlayerManagement\MHServerEmu.PlayerManagement.csproj" />
  </ItemGroup>

</Project>
