<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Platforms>x64</Platforms>
    <Configurations>Debug;Release;Debug 1.48;Release 1.48;Debug 1.53;Release 1.53</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="3.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MHServerEmu.DatabaseAccess\MHServerEmu.DatabaseAccess.csproj" />
    <ProjectReference Include="..\MHServerEmu.Leaderboards\MHServerEmu.Leaderboards.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="PostgreSQL\Scripts\SchemaVersion0.sql" />
    <None Remove="MySQL\Scripts\SchemaVersion0.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="PostgreSQL\Scripts\SchemaVersion0.sql" />
    <EmbeddedResource Include="MySQL\Scripts\SchemaVersion0.sql" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Dapper">
      <HintPath>..\..\dep\Dapper\Dapper.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.SQLite">
      <HintPath>..\..\dep\System.Data.SQLite\System.Data.SQLite.dll</HintPath>
    </Reference>
    <Reference Include="Npgsql">
      <HintPath>..\..\dep\Npgsql\Npgsql.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MySqlConnector">
      <HintPath>..\..\dep\MySqlConnector\MySqlConnector.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>..\..\dep\Npgsql\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>..\..\dep\Npgsql\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
