name: verify

on:
  push:
  pull_request:

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore MHServerEmu.sln
      - run: dotnet build MHServerEmu.sln --configuration Release --no-restore
      - run: dotnet test MHServerEmu.sln --configuration Release --no-build
